graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 119
         y 68
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 178
         y 145
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 240
         y 67
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 119
         y 210
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 184
         y 228
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 251
         y 185
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 114
         y 328
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 141
         y 393
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 194
         y 284
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 195
         y 358
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 268
         y 268
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 258
         y 350
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 11
      label ""
      weight 1.0
   ]
]