graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 217
         y 117
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 173
         y 200
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 267
         y 199
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 254
         y 272
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 301
         y 269
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 353
         y 260
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 100
         y 277
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 151
         y 292
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 203
         y 291
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 253
         y 348
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 9
      label ""
      weight 1.0
   ]
]