graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 142
         y 110
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 226
         y 110
      ]
   ]
   node [
      id 2
      label "A"
      graphics [
         x 142
         y 186
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 224
         y 186
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 142
         y 264
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 222
         y 263
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 3
      label ""
      weight 1.0
   ]
]