graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "A"
      graphics [
         x 94
         y 71
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 184
         y 71
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 184
         y 154
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 92
         y 154
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 92
         y 243
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 180
         y 243
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 2
      label ""
      weight 1.0
   ]
]