graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 159
         y 146
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 273
         y 150
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 276
         y 250
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 152
         y 246
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 148
         y 338
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 271
         y 346
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 2
      label ""
      weight 1.0
   ]
]